### ISSUE TITLE
Error in Plotting

### ISSUE THREAD

**Issue by thegameison** [fsschneider/DeepOBS#3]
Getting the following error trying to plot the results for the simple example as described in the documentation. I am running on Colab notebook with Python 3.6.8. 

matplotlib               3.0.3                
matplotlib-venn          0.11.5               
matplotlib2tikz          0.7.5  

Error message is:

/usr/local/lib/python3.6/dist-packages/matplotlib2tikz/save.py in _recurse(data, obj)
    340     """
    341     content = _ContentManager()
--> 342     for child in obj.get_children():
    343         # Some patches are Spines, too; skip those entirely.
    344         # See <https://github.com/nschloe/matplotlib2tikz/issues/277>.

AttributeError: 'str' object has no attribute 'get_children'

---

**To Do**

We will do the following steps for version 1.2.0:

- [ ] Update `matplotlib2tikz` to `tikzplotlib`
- [ ] Add tested version(s) to the documentation

**Comment by fsschneider** [comment]
Sorry for the late response, I did not see this issue until today.

Can you try to change your matplotlib2tikz version? Maybe try 0.6.18. I think I encountered this bug at one time, and could fix it with a different version of matplotlib2tikz.

We are currently working on a new version of DeepOBS, which should have this problem figured out (matplotlib2tikz is now deprecated and ported to tikzplotlib).
Until the release of the new version, you can checkout Aaron's branch, which contains the current beta version, where he fixed a lot of bugs and did quite a bit of refactoring.
This one also supports PyTorch.

 https://github.com/abahde/DeepOBS

**Comment by fsschneider** [comment]
We will do the following steps for version 1.2.0:

- [ ] Update `matplotlib2tikz` to `tikzplotlib`
- [ ] Add tested version(s) to the documentation

Added to the first post.

**Comment by fsschneider** [comment]
I justed tested it. I got the same error when using the latest `matplotlib2tikz` version (0.7.5). After downgrading to 0.6.18 it works.
We will move to `tikzplotlib` with the next release, hopefully this will solve our problems. For now, I hope that downgrading to version 0.6.18 is an option for you and solves your issue.

**Comment by fsschneider** [comment]
We've just update the stable version of DeepOBS. Now the version of matplotlib2tikz is fixed to 0.6.18 since there is no more support for it.
We will still update to tikzplotlib for version 1.2.0.
I will close this issue.
